name: Keala Kim
favicon: null
layout_spectrum: 0.6484261844307184
typography_spectrum: 0.7086746769491583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5969785959459841
  lightness: 0.6231825961731374
  saturation: 0.33259037462994456
  rhythmicContrast: 0.41845509014092386
purpose: []
