name: Keala Kim
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffefc'
    - '#cba68b'
    - '#d7bea8'
    - '#a66d62'
    - '#b0896c'
  brandStrength: 0.5969785959459841
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
